name: component
description: A new Flutter project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  theme:
    git:
      url: https://github.com/xiao6feng/ui.git
      path: theme

  two_dimensional_scrollables: ^0.0.4
  barcode_widget: ^2.0.4
  wechat_assets_picker: ^8.7.1
  image_picker: ^1.0.4
  photo_view: ^0.14.0
  lottie: ^2.7.0
  flutter_vibrate: ^1.3.0
  bot_toast: ^4.1.3
  carousel_slider: ^4.2.1
  intl: ^0.18.1
  get: ^4.6.6
  # common_utils:
  #   git: https://gitlab.ddyhr.com/app_foundation/package/common_utils.git
  # pagination:
  #   git:
  #     url: https://gitlab.ddyhr.com/app_foundation/package/api_service.git
  #     path: pagination
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.

flutter_gen:
  output: lib/gen/
  line_length: 80
  null_safety: true
  integrations:
    flutter_svg: true
    flare_flutter: true
  assets:
    enabled: true
  package_parameter_enabled: true


flutter:

  assets:
    - assets/images/icon/
    - assets/images/avatar/
    - assets/lottie/
    - assets/gif/

  fonts:
    - family: DIN-Medium
      fonts:
        - asset: assets/fonts/DIN-Medium.otf


# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
